import javax.swing.JOptionPane;
public class Menu extends javax.swing.JFrame {
    //Códigos dos botões; linha 225 até 260
    
    ControleCRUD control = new ControleCRUD(); //objeto para usar os recursos do CRUD
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelTitulo = new javax.swing.JLabel();
        LblMatricula = new javax.swing.JLabel();
        LblNome = new javax.swing.JLabel();
        LblDisciplina = new javax.swing.JLabel();
        BttAdicionar = new javax.swing.JButton();
        BttAtualizar = new javax.swing.JButton();
        BttBuscar = new javax.swing.JButton();
        BttDeletar = new javax.swing.JButton();
        TxtMatricula = new javax.swing.JTextField();
        TxtNome = new javax.swing.JTextField();
        TxtDisciplina = new javax.swing.JTextField();
        TxtMatricula2 = new javax.swing.JTextField();
        TxtNome2 = new javax.swing.JTextField();
        TxtDisciplina2 = new javax.swing.JTextField();
        LblMatricula2 = new javax.swing.JLabel();
        LblNome2 = new javax.swing.JLabel();
        LblDisciplina2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelTitulo.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 24)); // NOI18N
        LabelTitulo.setText("CRUD básico");

        LblMatricula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblMatricula.setText("MATRÍCULA");
        LblMatricula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LblNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblNome.setText("NOME");
        LblNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LblDisciplina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblDisciplina.setText("DISCIPLINA");
        LblDisciplina.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BttAdicionar.setText("Adicionar");
        BttAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttAdicionarActionPerformed(evt);
            }
        });

        BttAtualizar.setText("Atualizar");
        BttAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttAtualizarActionPerformed(evt);
            }
        });

        BttBuscar.setText("Buscar");
        BttBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttBuscarActionPerformed(evt);
            }
        });

        BttDeletar.setText("Deletar");
        BttDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttDeletarActionPerformed(evt);
            }
        });

        TxtMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtMatriculaActionPerformed(evt);
            }
        });

        TxtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNomeActionPerformed(evt);
            }
        });

        TxtDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDisciplinaActionPerformed(evt);
            }
        });

        TxtNome2.setEditable(false);

        TxtDisciplina2.setEditable(false);

        LblMatricula2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblMatricula2.setText("MATRÍCULA");
        LblMatricula2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LblNome2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblNome2.setText("NOME");
        LblNome2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LblDisciplina2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblDisciplina2.setText("DISCIPLINA");
        LblDisciplina2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BttAdicionar)
                                .addGap(72, 72, 72)
                                .addComponent(BttAtualizar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BttBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BttDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelTitulo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtMatricula2)
                                    .addComponent(LblMatricula2, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtNome2)
                                    .addComponent(LblNome2, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(LblMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                    .addComponent(TxtMatricula))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtNome)
                                    .addComponent(LblNome, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))))
                        .addGap(37, 37, 37)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblDisciplina, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(TxtDisciplina)
                    .addComponent(LblDisciplina2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtDisciplina2))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(LabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblMatricula)
                    .addComponent(LblDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblNome))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LblDisciplina2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtDisciplina2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BttAtualizar)
                                    .addComponent(BttAdicionar))
                                .addGap(18, 18, 18)
                                .addComponent(LblNome2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(LblMatricula2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TxtMatricula2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtNome2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BttDeletar)
                            .addComponent(BttBuscar))
                        .addGap(26, 26, 26))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtMatriculaActionPerformed

    private void TxtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNomeActionPerformed

    private void TxtDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDisciplinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDisciplinaActionPerformed

    private void BttAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttAdicionarActionPerformed
        if(control.buscar(TxtMatricula.getText())==null){ //verifica se nao existe
            Aluno a = new Aluno();
            a.setMatricula(TxtMatricula.getText());
            a.setNome(TxtNome.getText());
            a.setDisciplina(TxtDisciplina.getText()); //forma o objeto com os textos dos textFields
            control.adicionar(a);
            JOptionPane.showMessageDialog(rootPane, "Usuário adicionado");
        }else JOptionPane.showMessageDialog(rootPane, "Usuário já existente");                         
    }//GEN-LAST:event_BttAdicionarActionPerformed

    private void BttAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttAtualizarActionPerformed
        if(control.buscar(TxtMatricula.getText())!=null){ //verifica se existe
            Aluno a = new Aluno();
            a.setMatricula(TxtMatricula.getText());
            a.setNome(TxtNome.getText());
            a.setDisciplina(TxtDisciplina.getText());
            control.atualizar(a);
            JOptionPane.showMessageDialog(rootPane, "Usuário atualizado");
        }else JOptionPane.showMessageDialog(rootPane, "Usuário não existente");  
    }//GEN-LAST:event_BttAtualizarActionPerformed

    private void BttBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttBuscarActionPerformed
        if(control.buscar(TxtMatricula2.getText())!=null){
            Aluno a = control.buscar(TxtMatricula2.getText()); //objeto auxiliar
            TxtNome2.setText(a.getNome());
            TxtDisciplina2.setText(a.getDisciplina());
        }else JOptionPane.showMessageDialog(rootPane, "Usuário não existente");
    }//GEN-LAST:event_BttBuscarActionPerformed

    private void BttDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttDeletarActionPerformed
        if(control.buscar(TxtMatricula2.getText())!=null){
            control.deletar(TxtMatricula2.getText());
            JOptionPane.showMessageDialog(rootPane, "Usuário deletado");
        }else JOptionPane.showMessageDialog(rootPane, "Usuário não existente");
    }//GEN-LAST:event_BttDeletarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BttAdicionar;
    private javax.swing.JButton BttAtualizar;
    private javax.swing.JButton BttBuscar;
    private javax.swing.JButton BttDeletar;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JLabel LblDisciplina;
    private javax.swing.JLabel LblDisciplina2;
    private javax.swing.JLabel LblMatricula;
    private javax.swing.JLabel LblMatricula2;
    private javax.swing.JLabel LblNome;
    private javax.swing.JLabel LblNome2;
    private javax.swing.JTextField TxtDisciplina;
    private javax.swing.JTextField TxtDisciplina2;
    private javax.swing.JTextField TxtMatricula;
    private javax.swing.JTextField TxtMatricula2;
    private javax.swing.JTextField TxtNome;
    private javax.swing.JTextField TxtNome2;
    // End of variables declaration//GEN-END:variables
}
